version: '3.8'

services:
  redis-cache:
    image: redis:alpine
    container_name: redis-cache
    command: redis-server --maxmemory 5mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    networks:
      - futbol-net

  metrics:
    build: ./metrics
    container_name: metrics-service
    ports:
      - "5003:5003"
    networks:
      - futbol-net

  scraper:
    build: ./scraper
    container_name: scraper-service
    ports:
      - "5001:5001"
    environment:
      - METRICS_URL=http://metrics:5003/log
    networks:
      - futbol-net

  cache:
    build: ./cache
    container_name: cache-service
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis-cache
      - REDIS_PORT=6379
      - SCRAPER_URL=http://scraper:5001/scrape
      - METRICS_URL=http://metrics:5003/log
    depends_on:
      - redis-cache
      - scraper
      - metrics
    networks:
      - futbol-net

  traffic-generator:
    build: ./traffic-generator
    container_name: traffic-generator
    environment:
      - TARGET_URL=http://cache:5000/query
      - DISTRIBUTION=zipf  # Cambiar a 'uniform' según pruebas
    depends_on:
      - cache
    networks:
      - futbol-net

networks:
  futbol-net:
    driver: bridge